version: '3.8'
services:
  redis-cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    command: redis-server --bind redis-cache --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - pokedex-network

  pokedex-container:
    image: pokedex:1
    build:
      context: pokedex
      dockerfile: Dockerfile
    volumes:
      - /data/pokedex
    ports:
      - "8080:8080"
    networks:
      - pokedex-network
    depends_on:
      - redis-cache
    environment:
      - WAIT_HOSTS=redis-cache

  frontend:
    image: frontend:1
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: frontend
    volumes:
      - /frontend/node_modules
      - /frontend:/app
    networks:
      - pokedex-network
    depends_on:
      - redis-cache
      - pokedex-container
    ports:
      - "3000:3000"

volumes:
  cache:
    driver: local
  pokedex-container:
    driver: local

networks:
  pokedex-network:
    driver: bridge